default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: business_management_dev
  username: <%= Rails.application.credentials.dig(:database_user) %>
  password: <%= Rails.application.credentials.dig(:database_password) %>
  port: 5432
  host: localhost
  

test:
  <<: *default
  database: business_management_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
