default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: warehouse_backend_development
  username: <%= Rails.application.credentials.dig(:database_user) %>
  password: <%= Rails.application.credentials.dig(:database_password) %>

test:
  <<: *default
  database: warehouse_backend_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
